### ISSUE TITLE
Why is this project called fastMCD? I didn't see anything about fastMCD in the paper.

### ISSUE THREAD

**Issue by liaopan-lp** [kmyid/fastMCD#14]

**Comment by liaopan-lp** [comment]
Why is this project called fastMCD? I didn't see anything about fastMCD in the paper. #14

**Comment by kmyi** [comment]
It was a code name for the project back in the days. It's supposed to be an acronym for "fast **M**oving **C**amera object **D**etection"

**Comment by liaopan-lp** [comment]
Thanks!
