### ISSUE TITLE
Can't get the woman detected

### ISSUE THREAD

**Issue by yuyadanyadan** [kmyid/fastMCD#3]
Hi, sorry to disturb you! But my result cannot get the woman detected with NVCC compliers and nsight eclipse!
![qq 20170220093220](https://cloud.githubusercontent.com/assets/20216868/23109003/bba867fa-f74f-11e6-8813-043f903390f8.jpg)
This is the result!
Thank you very much!

**Comment by kmyi** [comment]
Hi, I saw this happen from a microsoft compiler when `abs` function was returning int instead of float, so I moved to `fabs` to be sure. Maybe it's because of the compiler you are using? can you try coercing the type to float after fabs calls? If it works, let me know.

Cheers,
Kwang

**Comment by yuyadanyadan** [comment]
Hi, I have tried coercing the type to float after fabs calls! And it doesn't work!

在 2017-02-20 17:46:55，"Kwang Moo Yi" <notifications@github.com> 写道：


Hi, I saw this happen from a microsoft compiler when abs function was returning int instead of float, so I moved to fabs to be sure. Maybe it's because of the compiler you are using? can you try coercing the type to float after fabs calls? If it works, let me know.

Cheers,
Kwang

**Comment by yuyadanyadan** [comment]
Hi， I try to debug. Alll the values of 'di' and 'dj' (in prob_mode.hpp) are 0. I don't know whether it effects!

**Comment by yuyadanyadan** [comment]
When I use the visual studio 2012 on the windows, I get the same result. Can you help me？Thank you , very much!

在 2017-02-20 17:46:55，"Kwang Moo Yi" <notifications@github.com> 写道：


Hi, I saw this happen from a microsoft compiler when abs function was returning int instead of float, so I moved to fabs to be sure. Maybe it's because of the compiler you are using? can you try coercing the type to float after fabs calls? If it works, let me know.

Cheers,
Kwang

**Comment by kmyi** [comment]
> Hi， I try to debug. Alll the values of 'di' and 'dj' (in prob_mode.hpp) are 0. I don't know whether it effects!

This is very weird. they should be floored indices in floats. I cloned the repository and simply rebuilt it from scratch but cannot reproduce your bug. I do not have a windows developer environment anymore, but I think my environment was visual studio 2012 as well, and it was working fine. Does the problem happen even on a freshly cloned repo?

FYI: Here's the result for the frame above.

![woman_frm00279](https://cloud.githubusercontent.com/assets/7147797/23159536/73b9be1a-f823-11e6-9c7f-1e5e9b91758d.png)

**Comment by yuyadanyadan** [comment]
Hi, thank you for your replying! Are the values of your 'di' and 'dj' all 0?? And I found the mat of 'h[9]' is almost approximate the unit matrix([1, 0, 0; 0, 1, 0; 0, 0, 1]). I'm very confused!
I only change the including files like opencv2/opencv.hpp instead of cv.h!
I hope your replying!
Thank you so much!

在 2017-02-21 17:51:34，"Kwang Moo Yi" <notifications@github.com> 写道：


Hi， I try to debug. Alll the values of 'di' and 'dj' (in prob_mode.hpp) are 0. I don't know whether it effects!

This is very weird. they should be floored indices in floats. I cloned the repository and simply rebuilt it from scratch but cannot reproduce your bug. I do not have a windows developer environment anymore, but I think my environment was visual studio 2012 as well, and it was working fine. Does the problem happen even on a freshly cloned repo?

FYI: Here's the result for the frame above.

**Comment by yuyadanyadan** [comment]
I'm so sorry! Maybe I change something which I don't know! When I use it on the others PC, I get the accurate results!
Sorry to disturb you again!
And thank you very much!






在 2017-02-21 17:51:34，"Kwang Moo Yi" <notifications@github.com> 写道：


Hi， I try to debug. Alll the values of 'di' and 'dj' (in prob_mode.hpp) are 0. I don't know whether it effects!

This is very weird. they should be floored indices in floats. I cloned the repository and simply rebuilt it from scratch but cannot reproduce your bug. I do not have a windows developer environment anymore, but I think my environment was visual studio 2012 as well, and it was working fine. Does the problem happen even on a freshly cloned repo?

FYI: Here's the result for the frame above.

**Comment by thuyndieu** [comment]
Hi, yuyadanyadan. I have the same results as you got at the first place. 
If it is possible and doesnot take so much your time, can you please give me the changes you made for this project?Thank you. I am using ubuntu, so do not know that it contributes any effects to the results?
