### ISSUE TITLE
Where do I get the motionCompensate(double h[9]) values

### ISSUE THREAD

**Issue by symisc** [kmyid/fastMCD#4]
If I only need prob_model.hpp to embed the motion detector in my test application, where can I can get the values for the **double h[9]** array parameter needed for _motionCompensate_

Thanks

Edit: I'm not using OpenCV at all

**Comment by kmyi** [comment]
Hello, 

The current code is using openCV's KLT to get the golobal motion as shown in lines 112--115 in MCDWrapper.cpp

```cpp
double h[9];
m_LucasKanade.RunTrack(imgGray, 0);
m_LucasKanade.GetHomography(h);
BGModel.motionCompensate(h);
```
If you don't want to use OpenCV, you probably need to implement that part yourself.

**Comment by symisc** [comment]
Is there any way to do that? if I always pass the default value, the result will be altered, right?

**Comment by kmyi** [comment]
> if I always pass the default value, the result will be altered, right?

I am not sure what you mean by default values.

**Comment by symisc** [comment]
Since I'm not using OpenCV anymore, I was looking for a way to get GetHomography() array paramaeter, so I have to look for another way to get these values
