### ISSUE TITLE
About the speed

### ISSUE THREAD

**Issue by gaochq** [kmyid/fastMCD#7]
Great job! But when I test this project, it takes almost 22ms per frame, which is slower than that in paper.

**Comment by kmyi** [comment]
Hello, 

I just ran the test and it returns about 6ms per frame on my MBP 2013 15inch on battery on the demo sequence.
The 5.8ms was measured with devices from 2013 and probable is even faster now.
Closing this issue as there' no information on the test conditions nor the OS etc.

**Comment by gaochq** [comment]
My test performed on Intel® Xeon(R) CPU E3-1230 V2 @ 3.30GHz, with Ubuntu 14.04.

**Comment by kmyi** [comment]
Are you looking at the numbers that are reported at the terminal when you run the demo?

**Comment by gaochq** [comment]
As shown below:
> PP: 1.10(ms)    OF: 16.96(ms)	BGM: 1.37(ms)
PP: 1.08(ms)	OF: 6.08(ms)	BGM: 3.44(ms)
PP: 1.19(ms)	OF: 11.99(ms)	BGM: 1.39(ms)	
PP: 1.66(ms)	
PP: 1.57(ms)	OF: 5.61(ms)	
PP: 1.43(ms)	OF: 6.52(ms)	BGM: 2.89(ms)	
PP: 0.80(ms)	OF: 4.89(ms)	BGM: 1.56(ms)	Total time: 	7
PP: 1.97(ms)	OF: 5.08(ms)	
PP: 1.35(ms)	OF: 4.45(ms)
.....
Cost 1.26011e+07 us
Average 26252.3us

And 26252.3us per frame contain the time for image read and copy..  
TIme for Pre-Processing , Motion Comp and Modeling takes almost 10ms

**Comment by kmyi** [comment]
Okay, 5.8 is the pure computation time excluding the IO. anyways, it seems that it’s still quite slowere than what it should be. I think you can do two things- 1. Enable all optimizations in gcc. do O3. it changes a lot. This includes settings for opencv as well, and you need to recompile opencv with O3 and fastmath on. 2. upgrade your compiler. The gcc version in 14.04 is old. newer ones provide more optimized code.

Kwang

**Comment by gaochq** [comment]
Many thanks!
