### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by Gasethata** [kmyid/fastMCD#8]
Hi
I tried the code and came across two errors. Its clear that the issue has something to do with opencv.
Either the opencv version or the compiler.
Any idea on how to go about this would be highly appreciated.

Below is the error I got:

/home/vip/Documents/Motion Detection Codes/fastMCD-master/src/KLTWrapper.cpp: In member function ‘void KLTWrapper::SwapData(IplImage*)’:
/home/vip/Documents/Motion Detection Codes/fastMCD-master/src/KLTWrapper.cpp:152:34: error: ‘cvCopyImage’ was not declared in this scope
  cvCopyImage(imgGray, imgPrevGray);
                                  ^
/home/vip/Documents/Motion Detection Codes/fastMCD-master/src/KLTWrapper.cpp: In member function ‘void KLTWrapper::MakeHomoGraphy(int*, int)’:
/home/vip/Documents/Motion Detection Codes/fastMCD-master/src/KLTWrapper.cpp:180:43: error: ‘CV_RANSAC’ was not declared in this scope
  if (!cvFindHomography(&_pt1, &_pt2, &_h, CV_RANSAC, 1))
                                           ^
/home/vip/Documents/Motion Detection Codes/fastMCD-master/src/KLTWrapper.cpp:180:55: error: ‘cvFindHomography’ was not declared in this scope
  if (!cvFindHomography(&_pt1, &_pt2, &_h, CV_RANSAC, 1))
                                                       ^
CMakeFiles/fastMCD.dir/build.make:110: recipe for target 'CMakeFiles/fastMCD.dir/src/KLTWrapper.cpp.o' failed
make[2]: *** [CMakeFiles/fastMCD.dir/src/KLTWrapper.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fastMCD.dir/all' failed
make[1]: *** [CMakeFiles/fastMCD.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kmyi** [comment]
Hi,

Are you using opencv3 by any chance? the current version is only compatible with opencv 2.4.X

Cheers,
Kwang

**Comment by Ankita-Singh-21** [comment]
For python use only RANSAC
For C++ use cv::RANSAC
